version: '3'

services:
  # client:
  #   build: .
  #   volumes:
  #     - "./client:/app"
  #   ports:
  #     - "3031:3000"
  #   depends_on:
  #     - api
  db:
    build: ./api/src/sql
    # networks:
    #   - docker_football_test_net
    # restart: always
    environment:
      MYSQL_DATABASE: footballDb
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
    ports:
    #   - "HOST_PORT:CONTAINER_PORT"
      - "3306:3306"
    # to allow connection from the native OS
    expose:
      - 3306
    volumes:
      - ./docker/data/db:/var/lib/mysql

  api:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: footballDb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      PORT: 3000
    volumes:
      - "./api:/app"
    ports:
      # - "HOST_PORT:CONTAINER_PORT"
      - "3000:3000"
    depends_on:
      - db
    # networks:
    #   - docker_football_test_net
    # links:
    #   - db
    # to allow connection from the native OS
    expose:
      - 3000

# networks:
#   docker_football_test_net:
#     driver: bridge