version: '3.1'

services:
  # client:
  #   build: .
  #   volumes:
  #     - "./client:/app"
  #   ports:
  #     - "3031:3000"
  #   depends_on:
  #     - api

  api:
    build: .
    volumes:
      - "./api:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: footballDb
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql